# Gives an internal IP so frontend can talk to backend
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
