# Runs and manages the Express frontend container pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: local-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

          # Checks if the application is still running
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

          # Checks if the application is ready to receive traffic
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

          env:
            - name: BACKEND_URL
              value: "http://backend-service:9000"
